name: CI
on:
  push:
    branches: [main]

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - run: git add .
      - run: git commit -m 构建
      - run: git push origin main:build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
